//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diploma.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жених, послушай наши наставленья!
        ///Невеста твоя просто загляденье!
        ///Бела, свежа, нежна словно цветок!
        ///Желаем, чтобы ты её берёг!
        ///
        ///Чтобы лелеял и любил свою отраду
        ///И с нею воспитал на загляденье чадо!
        ///Чтоб уважал и защищал свою супругу,
        ///От помощи не бегал с перепугу!
        ///
        ///Жене будь верным, не смотри налево,
        ///Ведь у тебя жена такая королева!
        ///Желаем вам любить друг друга вечно
        ///И быть счастливыми в союзе бесконечно!
        ///.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорогой жених и новоявленный муж! 
        ///Сегодня ты стал счастливым обладателем самого ценного подарка в твоей жизни — ты получил в законные супруги свою любимую женщину! 
        ///Береги её как зеницу ока, храни её от печалей и горестей, помогай во всех заботах насущных, люби её страстно и нежно!
        ///
        ///.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня день счастливый:
        ///Ведь ты нашел судьбу:
        ///Невеста всех красивей —
        ///Люби ее одну!
        ///
        ///А мы хотим поздравить
        ///Тебя, и пожелать:
        ///От всех невзгод житейских
        ///Жену оберегать.
        ///
        ///В семье авторитетом быть,
        ///Но тещу уважать,
        ///Заботы на двоих делить,
        ///А радость умножать!
        ///.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня все гости должны здесь признать —
        ///Невесты красивее не отыскать.
        ///Лицом — белолица, как лебедь стройна,
        ///К тому же добра, весела и умна.
        ///
        ///Умеет стирать, готовить и шить —
        ///Как можно такую, скажи, не любить.
        ///Чтоб муж твой и дальше гордился тобой,
        ///Будь любящей, верной и нежной женой.
        ///
        ///Готовь фрикасе, отбивные, рулет,
        ///Суши, рагу, а не просто омлет.
        ///Детишек расти, уют создавай,
        ///О саморазвитии не забывай.
        ///В салон красоты не забудь заходить,
        ///И муж тебя будет ценить, и любить.
        ///.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня все невесту поздравляем,
        ///Недавно стала ведь она женой,
        ///И от души, конечно, ей желаем,
        ///Всегда чтобы была красивою такой!
        ///
        ///Добра и мира ей в семье навечно,
        ///Не огорчалась, чтобы никогда,
        ///Пусть будет в жизни счастье бесконечно,
        ///А чувства будут свежими всегда!.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня — сравнивать с весной,
        ///В которой все цветы — о белом.
        ///Ведь в этот день виденья снов
        ///Все воплощаются. Так пела
        ///Душа, рождённая любить;
        ///Так много просящая места,
        ///Что все планеты, Марс, Юпитер
        ///Сводили вместе вас, невеста.
        ///День вашей свадьбы... Твой жених
        ///Так много выполнил «заданий»,
        ///Чтобы приблизить этот миг,
        ///И с ним тебя мы поздравляем!
        ///.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
    }
}
